[package]
name = "kiwi-app"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Kiwi keystroke visualizer settings app with tray icon"

[[bin]]
name = "kiwi"
path = "src/main.rs"

[dependencies]
env_logger.workspace = true
log.workspace = true
kiwi-common.workspace = true
zbus.workspace = true
tokio.workspace = true
ksni.workspace = true

[dependencies.libcosmic]
workspace = true
features = [
    "dbus-config",
    "multi-window",
    "tokio",
    "wayland",
    "winit",
    "wgpu",
]
